/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SuccessStoriesRouteImport } from './routes/success-stories'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RecentlyJoinedRouteImport } from './routes/recently-joined'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PremiumMembersRouteImport } from './routes/premium-members'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InterestsSentRouteImport } from './routes/interests-sent'
import { Route as InterestsReceivedRouteImport } from './routes/interests-received'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompleteProfileRouteImport } from './routes/complete-profile'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StaffUsersRouteImport } from './routes/staff.users'
import { Route as StaffNotesRouteImport } from './routes/staff.notes'
import { Route as StaffLeadsRouteImport } from './routes/staff.leads'
import { Route as StaffEditProfileRouteImport } from './routes/staff.edit-profile'
import { Route as StaffCreateUserRouteImport } from './routes/staff.create-user'
import { Route as ProfileIdRouteImport } from './routes/profile.$id'
import { Route as DashboardSupportTicketsRouteImport } from './routes/dashboard.support-tickets'
import { Route as DashboardSupportRouteImport } from './routes/dashboard.support'
import { Route as DashboardSubscriptionRouteImport } from './routes/dashboard.subscription'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardPrivacyRouteImport } from './routes/dashboard.privacy'
import { Route as DashboardPaymentsRouteImport } from './routes/dashboard.payments'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard.messages'
import { Route as DashboardEditProfileRouteImport } from './routes/dashboard.edit-profile'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSupportTicketsRouteImport } from './routes/admin.support-tickets'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminEditProfileRouteImport } from './routes/admin.edit-profile'
import { Route as AdminCmsRouteImport } from './routes/admin.cms'
import { Route as StaffLeadIdRouteImport } from './routes/staff.lead.$id'
import { Route as ProfileIdPoruthamRouteImport } from './routes/profile.$id.porutham'
import { Route as DashboardSupportTicketsIdRouteImport } from './routes/dashboard.support-tickets.$id'
import { Route as AdminStaffIdRouteImport } from './routes/admin.staff.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessStoriesRoute = SuccessStoriesRouteImport.update({
  id: '/success-stories',
  path: '/success-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentlyJoinedRoute = RecentlyJoinedRouteImport.update({
  id: '/recently-joined',
  path: '/recently-joined',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumMembersRoute = PremiumMembersRouteImport.update({
  id: '/premium-members',
  path: '/premium-members',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InterestsSentRoute = InterestsSentRouteImport.update({
  id: '/interests-sent',
  path: '/interests-sent',
  getParentRoute: () => rootRouteImport,
} as any)
const InterestsReceivedRoute = InterestsReceivedRouteImport.update({
  id: '/interests-received',
  path: '/interests-received',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteProfileRoute = CompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StaffUsersRoute = StaffUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => StaffRoute,
} as any)
const StaffNotesRoute = StaffNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => StaffRoute,
} as any)
const StaffLeadsRoute = StaffLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => StaffRoute,
} as any)
const StaffEditProfileRoute = StaffEditProfileRouteImport.update({
  id: '/edit-profile',
  path: '/edit-profile',
  getParentRoute: () => StaffRoute,
} as any)
const StaffCreateUserRoute = StaffCreateUserRouteImport.update({
  id: '/create-user',
  path: '/create-user',
  getParentRoute: () => StaffRoute,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSupportTicketsRoute = DashboardSupportTicketsRouteImport.update({
  id: '/support-tickets',
  path: '/support-tickets',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSupportRoute = DashboardSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSubscriptionRoute = DashboardSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPrivacyRoute = DashboardPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaymentsRoute = DashboardPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEditProfileRoute = DashboardEditProfileRouteImport.update({
  id: '/edit-profile',
  path: '/edit-profile',
  getParentRoute: () => DashboardRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportTicketsRoute = AdminSupportTicketsRouteImport.update({
  id: '/support-tickets',
  path: '/support-tickets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEditProfileRoute = AdminEditProfileRouteImport.update({
  id: '/edit-profile',
  path: '/edit-profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsRoute = AdminCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AdminRoute,
} as any)
const StaffLeadIdRoute = StaffLeadIdRouteImport.update({
  id: '/lead/$id',
  path: '/lead/$id',
  getParentRoute: () => StaffRoute,
} as any)
const ProfileIdPoruthamRoute = ProfileIdPoruthamRouteImport.update({
  id: '/porutham',
  path: '/porutham',
  getParentRoute: () => ProfileIdRoute,
} as any)
const DashboardSupportTicketsIdRoute =
  DashboardSupportTicketsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => DashboardSupportTicketsRoute,
  } as any)
const AdminStaffIdRoute = AdminStaffIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminStaffRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/browse': typeof BrowseRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/interests-received': typeof InterestsReceivedRoute
  '/interests-sent': typeof InterestsSentRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/premium-members': typeof PremiumMembersRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/recently-joined': typeof RecentlyJoinedRoute
  '/register': typeof RegisterRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/staff': typeof StaffRouteWithChildren
  '/success-stories': typeof SuccessStoriesRoute
  '/terms': typeof TermsRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/edit-profile': typeof AdminEditProfileRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/staff': typeof AdminStaffRouteWithChildren
  '/admin/support-tickets': typeof AdminSupportTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/edit-profile': typeof DashboardEditProfileRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/privacy': typeof DashboardPrivacyRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/subscription': typeof DashboardSubscriptionRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/support-tickets': typeof DashboardSupportTicketsRouteWithChildren
  '/profile/$id': typeof ProfileIdRouteWithChildren
  '/staff/create-user': typeof StaffCreateUserRoute
  '/staff/edit-profile': typeof StaffEditProfileRoute
  '/staff/leads': typeof StaffLeadsRoute
  '/staff/notes': typeof StaffNotesRoute
  '/staff/users': typeof StaffUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/admin/staff/$id': typeof AdminStaffIdRoute
  '/dashboard/support-tickets/$id': typeof DashboardSupportTicketsIdRoute
  '/profile/$id/porutham': typeof ProfileIdPoruthamRoute
  '/staff/lead/$id': typeof StaffLeadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/browse': typeof BrowseRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/interests-received': typeof InterestsReceivedRoute
  '/interests-sent': typeof InterestsSentRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/premium-members': typeof PremiumMembersRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/recently-joined': typeof RecentlyJoinedRoute
  '/register': typeof RegisterRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/terms': typeof TermsRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/edit-profile': typeof AdminEditProfileRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/staff': typeof AdminStaffRouteWithChildren
  '/admin/support-tickets': typeof AdminSupportTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/edit-profile': typeof DashboardEditProfileRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/privacy': typeof DashboardPrivacyRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/subscription': typeof DashboardSubscriptionRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/support-tickets': typeof DashboardSupportTicketsRouteWithChildren
  '/profile/$id': typeof ProfileIdRouteWithChildren
  '/staff/create-user': typeof StaffCreateUserRoute
  '/staff/edit-profile': typeof StaffEditProfileRoute
  '/staff/leads': typeof StaffLeadsRoute
  '/staff/notes': typeof StaffNotesRoute
  '/staff/users': typeof StaffUsersRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/staff': typeof StaffIndexRoute
  '/admin/staff/$id': typeof AdminStaffIdRoute
  '/dashboard/support-tickets/$id': typeof DashboardSupportTicketsIdRoute
  '/profile/$id/porutham': typeof ProfileIdPoruthamRoute
  '/staff/lead/$id': typeof StaffLeadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/browse': typeof BrowseRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/interests-received': typeof InterestsReceivedRoute
  '/interests-sent': typeof InterestsSentRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/premium-members': typeof PremiumMembersRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/recently-joined': typeof RecentlyJoinedRoute
  '/register': typeof RegisterRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/staff': typeof StaffRouteWithChildren
  '/success-stories': typeof SuccessStoriesRoute
  '/terms': typeof TermsRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/edit-profile': typeof AdminEditProfileRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/staff': typeof AdminStaffRouteWithChildren
  '/admin/support-tickets': typeof AdminSupportTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog_/$slug': typeof BlogSlugRoute
  '/dashboard/edit-profile': typeof DashboardEditProfileRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/privacy': typeof DashboardPrivacyRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/subscription': typeof DashboardSubscriptionRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/support-tickets': typeof DashboardSupportTicketsRouteWithChildren
  '/profile/$id': typeof ProfileIdRouteWithChildren
  '/staff/create-user': typeof StaffCreateUserRoute
  '/staff/edit-profile': typeof StaffEditProfileRoute
  '/staff/leads': typeof StaffLeadsRoute
  '/staff/notes': typeof StaffNotesRoute
  '/staff/users': typeof StaffUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/admin/staff/$id': typeof AdminStaffIdRoute
  '/dashboard/support-tickets/$id': typeof DashboardSupportTicketsIdRoute
  '/profile/$id/porutham': typeof ProfileIdPoruthamRoute
  '/staff/lead/$id': typeof StaffLeadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/browse'
    | '/complete-profile'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/forgot-password'
    | '/interests-received'
    | '/interests-sent'
    | '/login'
    | '/otp'
    | '/premium-members'
    | '/pricing'
    | '/privacy'
    | '/recently-joined'
    | '/register'
    | '/saved'
    | '/search'
    | '/staff'
    | '/success-stories'
    | '/terms'
    | '/admin/cms'
    | '/admin/edit-profile'
    | '/admin/leads'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/staff'
    | '/admin/support-tickets'
    | '/admin/users'
    | '/blog/$slug'
    | '/dashboard/edit-profile'
    | '/dashboard/messages'
    | '/dashboard/notifications'
    | '/dashboard/payments'
    | '/dashboard/privacy'
    | '/dashboard/profile'
    | '/dashboard/subscription'
    | '/dashboard/support'
    | '/dashboard/support-tickets'
    | '/profile/$id'
    | '/staff/create-user'
    | '/staff/edit-profile'
    | '/staff/leads'
    | '/staff/notes'
    | '/staff/users'
    | '/admin/'
    | '/blog/'
    | '/dashboard/'
    | '/staff/'
    | '/admin/staff/$id'
    | '/dashboard/support-tickets/$id'
    | '/profile/$id/porutham'
    | '/staff/lead/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/browse'
    | '/complete-profile'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/interests-received'
    | '/interests-sent'
    | '/login'
    | '/otp'
    | '/premium-members'
    | '/pricing'
    | '/privacy'
    | '/recently-joined'
    | '/register'
    | '/saved'
    | '/search'
    | '/success-stories'
    | '/terms'
    | '/admin/cms'
    | '/admin/edit-profile'
    | '/admin/leads'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/staff'
    | '/admin/support-tickets'
    | '/admin/users'
    | '/blog/$slug'
    | '/dashboard/edit-profile'
    | '/dashboard/messages'
    | '/dashboard/notifications'
    | '/dashboard/payments'
    | '/dashboard/privacy'
    | '/dashboard/profile'
    | '/dashboard/subscription'
    | '/dashboard/support'
    | '/dashboard/support-tickets'
    | '/profile/$id'
    | '/staff/create-user'
    | '/staff/edit-profile'
    | '/staff/leads'
    | '/staff/notes'
    | '/staff/users'
    | '/admin'
    | '/blog'
    | '/dashboard'
    | '/staff'
    | '/admin/staff/$id'
    | '/dashboard/support-tickets/$id'
    | '/profile/$id/porutham'
    | '/staff/lead/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/browse'
    | '/complete-profile'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/forgot-password'
    | '/interests-received'
    | '/interests-sent'
    | '/login'
    | '/otp'
    | '/premium-members'
    | '/pricing'
    | '/privacy'
    | '/recently-joined'
    | '/register'
    | '/saved'
    | '/search'
    | '/staff'
    | '/success-stories'
    | '/terms'
    | '/admin/cms'
    | '/admin/edit-profile'
    | '/admin/leads'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/staff'
    | '/admin/support-tickets'
    | '/admin/users'
    | '/blog_/$slug'
    | '/dashboard/edit-profile'
    | '/dashboard/messages'
    | '/dashboard/notifications'
    | '/dashboard/payments'
    | '/dashboard/privacy'
    | '/dashboard/profile'
    | '/dashboard/subscription'
    | '/dashboard/support'
    | '/dashboard/support-tickets'
    | '/profile/$id'
    | '/staff/create-user'
    | '/staff/edit-profile'
    | '/staff/leads'
    | '/staff/notes'
    | '/staff/users'
    | '/admin/'
    | '/blog/'
    | '/dashboard/'
    | '/staff/'
    | '/admin/staff/$id'
    | '/dashboard/support-tickets/$id'
    | '/profile/$id/porutham'
    | '/staff/lead/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BrowseRoute: typeof BrowseRoute
  CompleteProfileRoute: typeof CompleteProfileRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InterestsReceivedRoute: typeof InterestsReceivedRoute
  InterestsSentRoute: typeof InterestsSentRoute
  LoginRoute: typeof LoginRoute
  OtpRoute: typeof OtpRoute
  PremiumMembersRoute: typeof PremiumMembersRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RecentlyJoinedRoute: typeof RecentlyJoinedRoute
  RegisterRoute: typeof RegisterRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  StaffRoute: typeof StaffRouteWithChildren
  SuccessStoriesRoute: typeof SuccessStoriesRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ProfileIdRoute: typeof ProfileIdRouteWithChildren
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-stories': {
      id: '/success-stories'
      path: '/success-stories'
      fullPath: '/success-stories'
      preLoaderRoute: typeof SuccessStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recently-joined': {
      id: '/recently-joined'
      path: '/recently-joined'
      fullPath: '/recently-joined'
      preLoaderRoute: typeof RecentlyJoinedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium-members': {
      id: '/premium-members'
      path: '/premium-members'
      fullPath: '/premium-members'
      preLoaderRoute: typeof PremiumMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interests-sent': {
      id: '/interests-sent'
      path: '/interests-sent'
      fullPath: '/interests-sent'
      preLoaderRoute: typeof InterestsSentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interests-received': {
      id: '/interests-received'
      path: '/interests-received'
      fullPath: '/interests-received'
      preLoaderRoute: typeof InterestsReceivedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-profile': {
      id: '/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof CompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/staff/users': {
      id: '/staff/users'
      path: '/users'
      fullPath: '/staff/users'
      preLoaderRoute: typeof StaffUsersRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/notes': {
      id: '/staff/notes'
      path: '/notes'
      fullPath: '/staff/notes'
      preLoaderRoute: typeof StaffNotesRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/leads': {
      id: '/staff/leads'
      path: '/leads'
      fullPath: '/staff/leads'
      preLoaderRoute: typeof StaffLeadsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/edit-profile': {
      id: '/staff/edit-profile'
      path: '/edit-profile'
      fullPath: '/staff/edit-profile'
      preLoaderRoute: typeof StaffEditProfileRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/create-user': {
      id: '/staff/create-user'
      path: '/create-user'
      fullPath: '/staff/create-user'
      preLoaderRoute: typeof StaffCreateUserRouteImport
      parentRoute: typeof StaffRoute
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/support-tickets': {
      id: '/dashboard/support-tickets'
      path: '/support-tickets'
      fullPath: '/dashboard/support-tickets'
      preLoaderRoute: typeof DashboardSupportTicketsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/support': {
      id: '/dashboard/support'
      path: '/support'
      fullPath: '/dashboard/support'
      preLoaderRoute: typeof DashboardSupportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/subscription': {
      id: '/dashboard/subscription'
      path: '/subscription'
      fullPath: '/dashboard/subscription'
      preLoaderRoute: typeof DashboardSubscriptionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/privacy': {
      id: '/dashboard/privacy'
      path: '/privacy'
      fullPath: '/dashboard/privacy'
      preLoaderRoute: typeof DashboardPrivacyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payments': {
      id: '/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/edit-profile': {
      id: '/dashboard/edit-profile'
      path: '/edit-profile'
      fullPath: '/dashboard/edit-profile'
      preLoaderRoute: typeof DashboardEditProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support-tickets': {
      id: '/admin/support-tickets'
      path: '/support-tickets'
      fullPath: '/admin/support-tickets'
      preLoaderRoute: typeof AdminSupportTicketsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/edit-profile': {
      id: '/admin/edit-profile'
      path: '/edit-profile'
      fullPath: '/admin/edit-profile'
      preLoaderRoute: typeof AdminEditProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms': {
      id: '/admin/cms'
      path: '/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AdminCmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/staff/lead/$id': {
      id: '/staff/lead/$id'
      path: '/lead/$id'
      fullPath: '/staff/lead/$id'
      preLoaderRoute: typeof StaffLeadIdRouteImport
      parentRoute: typeof StaffRoute
    }
    '/profile/$id/porutham': {
      id: '/profile/$id/porutham'
      path: '/porutham'
      fullPath: '/profile/$id/porutham'
      preLoaderRoute: typeof ProfileIdPoruthamRouteImport
      parentRoute: typeof ProfileIdRoute
    }
    '/dashboard/support-tickets/$id': {
      id: '/dashboard/support-tickets/$id'
      path: '/$id'
      fullPath: '/dashboard/support-tickets/$id'
      preLoaderRoute: typeof DashboardSupportTicketsIdRouteImport
      parentRoute: typeof DashboardSupportTicketsRoute
    }
    '/admin/staff/$id': {
      id: '/admin/staff/$id'
      path: '/$id'
      fullPath: '/admin/staff/$id'
      preLoaderRoute: typeof AdminStaffIdRouteImport
      parentRoute: typeof AdminStaffRoute
    }
  }
}

interface AdminStaffRouteChildren {
  AdminStaffIdRoute: typeof AdminStaffIdRoute
}

const AdminStaffRouteChildren: AdminStaffRouteChildren = {
  AdminStaffIdRoute: AdminStaffIdRoute,
}

const AdminStaffRouteWithChildren = AdminStaffRoute._addFileChildren(
  AdminStaffRouteChildren,
)

interface AdminRouteChildren {
  AdminCmsRoute: typeof AdminCmsRoute
  AdminEditProfileRoute: typeof AdminEditProfileRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminStaffRoute: typeof AdminStaffRouteWithChildren
  AdminSupportTicketsRoute: typeof AdminSupportTicketsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCmsRoute: AdminCmsRoute,
  AdminEditProfileRoute: AdminEditProfileRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminStaffRoute: AdminStaffRouteWithChildren,
  AdminSupportTicketsRoute: AdminSupportTicketsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardSupportTicketsRouteChildren {
  DashboardSupportTicketsIdRoute: typeof DashboardSupportTicketsIdRoute
}

const DashboardSupportTicketsRouteChildren: DashboardSupportTicketsRouteChildren =
  {
    DashboardSupportTicketsIdRoute: DashboardSupportTicketsIdRoute,
  }

const DashboardSupportTicketsRouteWithChildren =
  DashboardSupportTicketsRoute._addFileChildren(
    DashboardSupportTicketsRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardEditProfileRoute: typeof DashboardEditProfileRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardPaymentsRoute: typeof DashboardPaymentsRoute
  DashboardPrivacyRoute: typeof DashboardPrivacyRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSubscriptionRoute: typeof DashboardSubscriptionRoute
  DashboardSupportRoute: typeof DashboardSupportRoute
  DashboardSupportTicketsRoute: typeof DashboardSupportTicketsRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardEditProfileRoute: DashboardEditProfileRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardPaymentsRoute: DashboardPaymentsRoute,
  DashboardPrivacyRoute: DashboardPrivacyRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSubscriptionRoute: DashboardSubscriptionRoute,
  DashboardSupportRoute: DashboardSupportRoute,
  DashboardSupportTicketsRoute: DashboardSupportTicketsRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface StaffRouteChildren {
  StaffCreateUserRoute: typeof StaffCreateUserRoute
  StaffEditProfileRoute: typeof StaffEditProfileRoute
  StaffLeadsRoute: typeof StaffLeadsRoute
  StaffNotesRoute: typeof StaffNotesRoute
  StaffUsersRoute: typeof StaffUsersRoute
  StaffIndexRoute: typeof StaffIndexRoute
  StaffLeadIdRoute: typeof StaffLeadIdRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffCreateUserRoute: StaffCreateUserRoute,
  StaffEditProfileRoute: StaffEditProfileRoute,
  StaffLeadsRoute: StaffLeadsRoute,
  StaffNotesRoute: StaffNotesRoute,
  StaffUsersRoute: StaffUsersRoute,
  StaffIndexRoute: StaffIndexRoute,
  StaffLeadIdRoute: StaffLeadIdRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

interface ProfileIdRouteChildren {
  ProfileIdPoruthamRoute: typeof ProfileIdPoruthamRoute
}

const ProfileIdRouteChildren: ProfileIdRouteChildren = {
  ProfileIdPoruthamRoute: ProfileIdPoruthamRoute,
}

const ProfileIdRouteWithChildren = ProfileIdRoute._addFileChildren(
  ProfileIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BrowseRoute: BrowseRoute,
  CompleteProfileRoute: CompleteProfileRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InterestsReceivedRoute: InterestsReceivedRoute,
  InterestsSentRoute: InterestsSentRoute,
  LoginRoute: LoginRoute,
  OtpRoute: OtpRoute,
  PremiumMembersRoute: PremiumMembersRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RecentlyJoinedRoute: RecentlyJoinedRoute,
  RegisterRoute: RegisterRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  StaffRoute: StaffRouteWithChildren,
  SuccessStoriesRoute: SuccessStoriesRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  ProfileIdRoute: ProfileIdRouteWithChildren,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
