/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UkControlRouteImport } from './routes/uk-control'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SuccessStoriesRouteImport } from './routes/success-stories'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RecentlyJoinedRouteImport } from './routes/recently-joined'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PremiumMembersRouteImport } from './routes/premium-members'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InterestsSentRouteImport } from './routes/interests-sent'
import { Route as InterestsReceivedRouteImport } from './routes/interests-received'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompleteProfileRouteImport } from './routes/complete-profile'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UkControlIndexRouteImport } from './routes/uk-control.index'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as UkControlUsersRouteImport } from './routes/uk-control.users'
import { Route as UkControlSupportTicketsRouteImport } from './routes/uk-control.support-tickets'
import { Route as UkControlStaffRouteImport } from './routes/uk-control.staff'
import { Route as UkControlReportsRouteImport } from './routes/uk-control.reports'
import { Route as UkControlPaymentsRouteImport } from './routes/uk-control.payments'
import { Route as UkControlLeadsRouteImport } from './routes/uk-control.leads'
import { Route as UkControlEditProfileRouteImport } from './routes/uk-control.edit-profile'
import { Route as UkControlCmsRouteImport } from './routes/uk-control.cms'
import { Route as UkControlBulkUploadRouteImport } from './routes/uk-control.bulk-upload'
import { Route as StaffUsersRouteImport } from './routes/staff.users'
import { Route as StaffNotesRouteImport } from './routes/staff.notes'
import { Route as StaffLeadsRouteImport } from './routes/staff.leads'
import { Route as StaffEditProfileRouteImport } from './routes/staff.edit-profile'
import { Route as StaffCreateUserRouteImport } from './routes/staff.create-user'
import { Route as ProfileIdRouteImport } from './routes/profile.$id'
import { Route as DashboardSupportTicketsRouteImport } from './routes/dashboard.support-tickets'
import { Route as DashboardSupportRouteImport } from './routes/dashboard.support'
import { Route as DashboardSubscriptionRouteImport } from './routes/dashboard.subscription'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardPrivacyRouteImport } from './routes/dashboard.privacy'
import { Route as DashboardPaymentsRouteImport } from './routes/dashboard.payments'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard.messages'
import { Route as DashboardEditProfileRouteImport } from './routes/dashboard.edit-profile'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'
import { Route as UkControlStaffIdRouteImport } from './routes/uk-control.staff.$id'
import { Route as StaffLeadIdRouteImport } from './routes/staff.lead.$id'
import { Route as ProfileIdPoruthamRouteImport } from './routes/profile.$id.porutham'
import { Route as DashboardSupportTicketsIdRouteImport } from './routes/dashboard.support-tickets.$id'

const UkControlRoute = UkControlRouteImport.update({
  id: '/uk-control',
  path: '/uk-control',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessStoriesRoute = SuccessStoriesRouteImport.update({
  id: '/success-stories',
  path: '/success-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentlyJoinedRoute = RecentlyJoinedRouteImport.update({
  id: '/recently-joined',
  path: '/recently-joined',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumMembersRoute = PremiumMembersRouteImport.update({
  id: '/premium-members',
  path: '/premium-members',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InterestsSentRoute = InterestsSentRouteImport.update({
  id: '/interests-sent',
  path: '/interests-sent',
  getParentRoute: () => rootRouteImport,
} as any)
const InterestsReceivedRoute = InterestsReceivedRouteImport.update({
  id: '/interests-received',
  path: '/interests-received',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteProfileRoute = CompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UkControlIndexRoute = UkControlIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UkControlRoute,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const UkControlUsersRoute = UkControlUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => UkControlRoute,
} as any)
const UkControlSupportTicketsRoute = UkControlSupportTicketsRouteImport.update({
  id: '/support-tickets',
  path: '/support-tickets',
  getParentRoute: () => UkControlRoute,
} as any)
const UkControlStaffRoute = UkControlStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => UkControlRoute,
} as any)
const UkControlReportsRoute = UkControlReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => UkControlRoute,
} as any)
const UkControlPaymentsRoute = UkControlPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => UkControlRoute,
} as any)
const UkControlLeadsRoute = UkControlLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => UkControlRoute,
} as any)
const UkControlEditProfileRoute = UkControlEditProfileRouteImport.update({
  id: '/edit-profile',
  path: '/edit-profile',
  getParentRoute: () => UkControlRoute,
} as any)
const UkControlCmsRoute = UkControlCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => UkControlRoute,
} as any)
const UkControlBulkUploadRoute = UkControlBulkUploadRouteImport.update({
  id: '/bulk-upload',
  path: '/bulk-upload',
  getParentRoute: () => UkControlRoute,
} as any)
const StaffUsersRoute = StaffUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => StaffRoute,
} as any)
const StaffNotesRoute = StaffNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => StaffRoute,
} as any)
const StaffLeadsRoute = StaffLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => StaffRoute,
} as any)
const StaffEditProfileRoute = StaffEditProfileRouteImport.update({
  id: '/edit-profile',
  path: '/edit-profile',
  getParentRoute: () => StaffRoute,
} as any)
const StaffCreateUserRoute = StaffCreateUserRouteImport.update({
  id: '/create-user',
  path: '/create-user',
  getParentRoute: () => StaffRoute,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSupportTicketsRoute = DashboardSupportTicketsRouteImport.update({
  id: '/support-tickets',
  path: '/support-tickets',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSupportRoute = DashboardSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSubscriptionRoute = DashboardSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPrivacyRoute = DashboardPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaymentsRoute = DashboardPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEditProfileRoute = DashboardEditProfileRouteImport.update({
  id: '/edit-profile',
  path: '/edit-profile',
  getParentRoute: () => DashboardRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UkControlStaffIdRoute = UkControlStaffIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => UkControlStaffRoute,
} as any)
const StaffLeadIdRoute = StaffLeadIdRouteImport.update({
  id: '/lead/$id',
  path: '/lead/$id',
  getParentRoute: () => StaffRoute,
} as any)
const ProfileIdPoruthamRoute = ProfileIdPoruthamRouteImport.update({
  id: '/porutham',
  path: '/porutham',
  getParentRoute: () => ProfileIdRoute,
} as any)
const DashboardSupportTicketsIdRoute =
  DashboardSupportTicketsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => DashboardSupportTicketsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/browse': typeof BrowseRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/interests-received': typeof InterestsReceivedRoute
  '/interests-sent': typeof InterestsSentRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/premium-members': typeof PremiumMembersRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/recently-joined': typeof RecentlyJoinedRoute
  '/register': typeof RegisterRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/staff': typeof StaffRouteWithChildren
  '/success-stories': typeof SuccessStoriesRoute
  '/terms': typeof TermsRoute
  '/uk-control': typeof UkControlRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/edit-profile': typeof DashboardEditProfileRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/privacy': typeof DashboardPrivacyRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/subscription': typeof DashboardSubscriptionRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/support-tickets': typeof DashboardSupportTicketsRouteWithChildren
  '/profile/$id': typeof ProfileIdRouteWithChildren
  '/staff/create-user': typeof StaffCreateUserRoute
  '/staff/edit-profile': typeof StaffEditProfileRoute
  '/staff/leads': typeof StaffLeadsRoute
  '/staff/notes': typeof StaffNotesRoute
  '/staff/users': typeof StaffUsersRoute
  '/uk-control/bulk-upload': typeof UkControlBulkUploadRoute
  '/uk-control/cms': typeof UkControlCmsRoute
  '/uk-control/edit-profile': typeof UkControlEditProfileRoute
  '/uk-control/leads': typeof UkControlLeadsRoute
  '/uk-control/payments': typeof UkControlPaymentsRoute
  '/uk-control/reports': typeof UkControlReportsRoute
  '/uk-control/staff': typeof UkControlStaffRouteWithChildren
  '/uk-control/support-tickets': typeof UkControlSupportTicketsRoute
  '/uk-control/users': typeof UkControlUsersRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/uk-control/': typeof UkControlIndexRoute
  '/dashboard/support-tickets/$id': typeof DashboardSupportTicketsIdRoute
  '/profile/$id/porutham': typeof ProfileIdPoruthamRoute
  '/staff/lead/$id': typeof StaffLeadIdRoute
  '/uk-control/staff/$id': typeof UkControlStaffIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/browse': typeof BrowseRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/interests-received': typeof InterestsReceivedRoute
  '/interests-sent': typeof InterestsSentRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/premium-members': typeof PremiumMembersRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/recently-joined': typeof RecentlyJoinedRoute
  '/register': typeof RegisterRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/edit-profile': typeof DashboardEditProfileRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/privacy': typeof DashboardPrivacyRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/subscription': typeof DashboardSubscriptionRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/support-tickets': typeof DashboardSupportTicketsRouteWithChildren
  '/profile/$id': typeof ProfileIdRouteWithChildren
  '/staff/create-user': typeof StaffCreateUserRoute
  '/staff/edit-profile': typeof StaffEditProfileRoute
  '/staff/leads': typeof StaffLeadsRoute
  '/staff/notes': typeof StaffNotesRoute
  '/staff/users': typeof StaffUsersRoute
  '/uk-control/bulk-upload': typeof UkControlBulkUploadRoute
  '/uk-control/cms': typeof UkControlCmsRoute
  '/uk-control/edit-profile': typeof UkControlEditProfileRoute
  '/uk-control/leads': typeof UkControlLeadsRoute
  '/uk-control/payments': typeof UkControlPaymentsRoute
  '/uk-control/reports': typeof UkControlReportsRoute
  '/uk-control/staff': typeof UkControlStaffRouteWithChildren
  '/uk-control/support-tickets': typeof UkControlSupportTicketsRoute
  '/uk-control/users': typeof UkControlUsersRoute
  '/blog': typeof BlogIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/staff': typeof StaffIndexRoute
  '/uk-control': typeof UkControlIndexRoute
  '/dashboard/support-tickets/$id': typeof DashboardSupportTicketsIdRoute
  '/profile/$id/porutham': typeof ProfileIdPoruthamRoute
  '/staff/lead/$id': typeof StaffLeadIdRoute
  '/uk-control/staff/$id': typeof UkControlStaffIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/browse': typeof BrowseRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/interests-received': typeof InterestsReceivedRoute
  '/interests-sent': typeof InterestsSentRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/premium-members': typeof PremiumMembersRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/recently-joined': typeof RecentlyJoinedRoute
  '/register': typeof RegisterRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/staff': typeof StaffRouteWithChildren
  '/success-stories': typeof SuccessStoriesRoute
  '/terms': typeof TermsRoute
  '/uk-control': typeof UkControlRouteWithChildren
  '/blog_/$slug': typeof BlogSlugRoute
  '/dashboard/edit-profile': typeof DashboardEditProfileRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/privacy': typeof DashboardPrivacyRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/subscription': typeof DashboardSubscriptionRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/support-tickets': typeof DashboardSupportTicketsRouteWithChildren
  '/profile/$id': typeof ProfileIdRouteWithChildren
  '/staff/create-user': typeof StaffCreateUserRoute
  '/staff/edit-profile': typeof StaffEditProfileRoute
  '/staff/leads': typeof StaffLeadsRoute
  '/staff/notes': typeof StaffNotesRoute
  '/staff/users': typeof StaffUsersRoute
  '/uk-control/bulk-upload': typeof UkControlBulkUploadRoute
  '/uk-control/cms': typeof UkControlCmsRoute
  '/uk-control/edit-profile': typeof UkControlEditProfileRoute
  '/uk-control/leads': typeof UkControlLeadsRoute
  '/uk-control/payments': typeof UkControlPaymentsRoute
  '/uk-control/reports': typeof UkControlReportsRoute
  '/uk-control/staff': typeof UkControlStaffRouteWithChildren
  '/uk-control/support-tickets': typeof UkControlSupportTicketsRoute
  '/uk-control/users': typeof UkControlUsersRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/uk-control/': typeof UkControlIndexRoute
  '/dashboard/support-tickets/$id': typeof DashboardSupportTicketsIdRoute
  '/profile/$id/porutham': typeof ProfileIdPoruthamRoute
  '/staff/lead/$id': typeof StaffLeadIdRoute
  '/uk-control/staff/$id': typeof UkControlStaffIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/browse'
    | '/complete-profile'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/forgot-password'
    | '/interests-received'
    | '/interests-sent'
    | '/login'
    | '/otp'
    | '/premium-members'
    | '/pricing'
    | '/privacy'
    | '/recently-joined'
    | '/register'
    | '/saved'
    | '/search'
    | '/staff'
    | '/success-stories'
    | '/terms'
    | '/uk-control'
    | '/blog/$slug'
    | '/dashboard/edit-profile'
    | '/dashboard/messages'
    | '/dashboard/notifications'
    | '/dashboard/payments'
    | '/dashboard/privacy'
    | '/dashboard/profile'
    | '/dashboard/subscription'
    | '/dashboard/support'
    | '/dashboard/support-tickets'
    | '/profile/$id'
    | '/staff/create-user'
    | '/staff/edit-profile'
    | '/staff/leads'
    | '/staff/notes'
    | '/staff/users'
    | '/uk-control/bulk-upload'
    | '/uk-control/cms'
    | '/uk-control/edit-profile'
    | '/uk-control/leads'
    | '/uk-control/payments'
    | '/uk-control/reports'
    | '/uk-control/staff'
    | '/uk-control/support-tickets'
    | '/uk-control/users'
    | '/blog/'
    | '/dashboard/'
    | '/staff/'
    | '/uk-control/'
    | '/dashboard/support-tickets/$id'
    | '/profile/$id/porutham'
    | '/staff/lead/$id'
    | '/uk-control/staff/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/browse'
    | '/complete-profile'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/interests-received'
    | '/interests-sent'
    | '/login'
    | '/otp'
    | '/premium-members'
    | '/pricing'
    | '/privacy'
    | '/recently-joined'
    | '/register'
    | '/saved'
    | '/search'
    | '/success-stories'
    | '/terms'
    | '/blog/$slug'
    | '/dashboard/edit-profile'
    | '/dashboard/messages'
    | '/dashboard/notifications'
    | '/dashboard/payments'
    | '/dashboard/privacy'
    | '/dashboard/profile'
    | '/dashboard/subscription'
    | '/dashboard/support'
    | '/dashboard/support-tickets'
    | '/profile/$id'
    | '/staff/create-user'
    | '/staff/edit-profile'
    | '/staff/leads'
    | '/staff/notes'
    | '/staff/users'
    | '/uk-control/bulk-upload'
    | '/uk-control/cms'
    | '/uk-control/edit-profile'
    | '/uk-control/leads'
    | '/uk-control/payments'
    | '/uk-control/reports'
    | '/uk-control/staff'
    | '/uk-control/support-tickets'
    | '/uk-control/users'
    | '/blog'
    | '/dashboard'
    | '/staff'
    | '/uk-control'
    | '/dashboard/support-tickets/$id'
    | '/profile/$id/porutham'
    | '/staff/lead/$id'
    | '/uk-control/staff/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/browse'
    | '/complete-profile'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/forgot-password'
    | '/interests-received'
    | '/interests-sent'
    | '/login'
    | '/otp'
    | '/premium-members'
    | '/pricing'
    | '/privacy'
    | '/recently-joined'
    | '/register'
    | '/saved'
    | '/search'
    | '/staff'
    | '/success-stories'
    | '/terms'
    | '/uk-control'
    | '/blog_/$slug'
    | '/dashboard/edit-profile'
    | '/dashboard/messages'
    | '/dashboard/notifications'
    | '/dashboard/payments'
    | '/dashboard/privacy'
    | '/dashboard/profile'
    | '/dashboard/subscription'
    | '/dashboard/support'
    | '/dashboard/support-tickets'
    | '/profile/$id'
    | '/staff/create-user'
    | '/staff/edit-profile'
    | '/staff/leads'
    | '/staff/notes'
    | '/staff/users'
    | '/uk-control/bulk-upload'
    | '/uk-control/cms'
    | '/uk-control/edit-profile'
    | '/uk-control/leads'
    | '/uk-control/payments'
    | '/uk-control/reports'
    | '/uk-control/staff'
    | '/uk-control/support-tickets'
    | '/uk-control/users'
    | '/blog/'
    | '/dashboard/'
    | '/staff/'
    | '/uk-control/'
    | '/dashboard/support-tickets/$id'
    | '/profile/$id/porutham'
    | '/staff/lead/$id'
    | '/uk-control/staff/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BrowseRoute: typeof BrowseRoute
  CompleteProfileRoute: typeof CompleteProfileRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InterestsReceivedRoute: typeof InterestsReceivedRoute
  InterestsSentRoute: typeof InterestsSentRoute
  LoginRoute: typeof LoginRoute
  OtpRoute: typeof OtpRoute
  PremiumMembersRoute: typeof PremiumMembersRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RecentlyJoinedRoute: typeof RecentlyJoinedRoute
  RegisterRoute: typeof RegisterRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  StaffRoute: typeof StaffRouteWithChildren
  SuccessStoriesRoute: typeof SuccessStoriesRoute
  TermsRoute: typeof TermsRoute
  UkControlRoute: typeof UkControlRouteWithChildren
  BlogSlugRoute: typeof BlogSlugRoute
  ProfileIdRoute: typeof ProfileIdRouteWithChildren
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uk-control': {
      id: '/uk-control'
      path: '/uk-control'
      fullPath: '/uk-control'
      preLoaderRoute: typeof UkControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-stories': {
      id: '/success-stories'
      path: '/success-stories'
      fullPath: '/success-stories'
      preLoaderRoute: typeof SuccessStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recently-joined': {
      id: '/recently-joined'
      path: '/recently-joined'
      fullPath: '/recently-joined'
      preLoaderRoute: typeof RecentlyJoinedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium-members': {
      id: '/premium-members'
      path: '/premium-members'
      fullPath: '/premium-members'
      preLoaderRoute: typeof PremiumMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interests-sent': {
      id: '/interests-sent'
      path: '/interests-sent'
      fullPath: '/interests-sent'
      preLoaderRoute: typeof InterestsSentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interests-received': {
      id: '/interests-received'
      path: '/interests-received'
      fullPath: '/interests-received'
      preLoaderRoute: typeof InterestsReceivedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-profile': {
      id: '/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof CompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uk-control/': {
      id: '/uk-control/'
      path: '/'
      fullPath: '/uk-control/'
      preLoaderRoute: typeof UkControlIndexRouteImport
      parentRoute: typeof UkControlRoute
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uk-control/users': {
      id: '/uk-control/users'
      path: '/users'
      fullPath: '/uk-control/users'
      preLoaderRoute: typeof UkControlUsersRouteImport
      parentRoute: typeof UkControlRoute
    }
    '/uk-control/support-tickets': {
      id: '/uk-control/support-tickets'
      path: '/support-tickets'
      fullPath: '/uk-control/support-tickets'
      preLoaderRoute: typeof UkControlSupportTicketsRouteImport
      parentRoute: typeof UkControlRoute
    }
    '/uk-control/staff': {
      id: '/uk-control/staff'
      path: '/staff'
      fullPath: '/uk-control/staff'
      preLoaderRoute: typeof UkControlStaffRouteImport
      parentRoute: typeof UkControlRoute
    }
    '/uk-control/reports': {
      id: '/uk-control/reports'
      path: '/reports'
      fullPath: '/uk-control/reports'
      preLoaderRoute: typeof UkControlReportsRouteImport
      parentRoute: typeof UkControlRoute
    }
    '/uk-control/payments': {
      id: '/uk-control/payments'
      path: '/payments'
      fullPath: '/uk-control/payments'
      preLoaderRoute: typeof UkControlPaymentsRouteImport
      parentRoute: typeof UkControlRoute
    }
    '/uk-control/leads': {
      id: '/uk-control/leads'
      path: '/leads'
      fullPath: '/uk-control/leads'
      preLoaderRoute: typeof UkControlLeadsRouteImport
      parentRoute: typeof UkControlRoute
    }
    '/uk-control/edit-profile': {
      id: '/uk-control/edit-profile'
      path: '/edit-profile'
      fullPath: '/uk-control/edit-profile'
      preLoaderRoute: typeof UkControlEditProfileRouteImport
      parentRoute: typeof UkControlRoute
    }
    '/uk-control/cms': {
      id: '/uk-control/cms'
      path: '/cms'
      fullPath: '/uk-control/cms'
      preLoaderRoute: typeof UkControlCmsRouteImport
      parentRoute: typeof UkControlRoute
    }
    '/uk-control/bulk-upload': {
      id: '/uk-control/bulk-upload'
      path: '/bulk-upload'
      fullPath: '/uk-control/bulk-upload'
      preLoaderRoute: typeof UkControlBulkUploadRouteImport
      parentRoute: typeof UkControlRoute
    }
    '/staff/users': {
      id: '/staff/users'
      path: '/users'
      fullPath: '/staff/users'
      preLoaderRoute: typeof StaffUsersRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/notes': {
      id: '/staff/notes'
      path: '/notes'
      fullPath: '/staff/notes'
      preLoaderRoute: typeof StaffNotesRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/leads': {
      id: '/staff/leads'
      path: '/leads'
      fullPath: '/staff/leads'
      preLoaderRoute: typeof StaffLeadsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/edit-profile': {
      id: '/staff/edit-profile'
      path: '/edit-profile'
      fullPath: '/staff/edit-profile'
      preLoaderRoute: typeof StaffEditProfileRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/create-user': {
      id: '/staff/create-user'
      path: '/create-user'
      fullPath: '/staff/create-user'
      preLoaderRoute: typeof StaffCreateUserRouteImport
      parentRoute: typeof StaffRoute
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/support-tickets': {
      id: '/dashboard/support-tickets'
      path: '/support-tickets'
      fullPath: '/dashboard/support-tickets'
      preLoaderRoute: typeof DashboardSupportTicketsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/support': {
      id: '/dashboard/support'
      path: '/support'
      fullPath: '/dashboard/support'
      preLoaderRoute: typeof DashboardSupportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/subscription': {
      id: '/dashboard/subscription'
      path: '/subscription'
      fullPath: '/dashboard/subscription'
      preLoaderRoute: typeof DashboardSubscriptionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/privacy': {
      id: '/dashboard/privacy'
      path: '/privacy'
      fullPath: '/dashboard/privacy'
      preLoaderRoute: typeof DashboardPrivacyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payments': {
      id: '/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/edit-profile': {
      id: '/dashboard/edit-profile'
      path: '/edit-profile'
      fullPath: '/dashboard/edit-profile'
      preLoaderRoute: typeof DashboardEditProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uk-control/staff/$id': {
      id: '/uk-control/staff/$id'
      path: '/$id'
      fullPath: '/uk-control/staff/$id'
      preLoaderRoute: typeof UkControlStaffIdRouteImport
      parentRoute: typeof UkControlStaffRoute
    }
    '/staff/lead/$id': {
      id: '/staff/lead/$id'
      path: '/lead/$id'
      fullPath: '/staff/lead/$id'
      preLoaderRoute: typeof StaffLeadIdRouteImport
      parentRoute: typeof StaffRoute
    }
    '/profile/$id/porutham': {
      id: '/profile/$id/porutham'
      path: '/porutham'
      fullPath: '/profile/$id/porutham'
      preLoaderRoute: typeof ProfileIdPoruthamRouteImport
      parentRoute: typeof ProfileIdRoute
    }
    '/dashboard/support-tickets/$id': {
      id: '/dashboard/support-tickets/$id'
      path: '/$id'
      fullPath: '/dashboard/support-tickets/$id'
      preLoaderRoute: typeof DashboardSupportTicketsIdRouteImport
      parentRoute: typeof DashboardSupportTicketsRoute
    }
  }
}

interface DashboardSupportTicketsRouteChildren {
  DashboardSupportTicketsIdRoute: typeof DashboardSupportTicketsIdRoute
}

const DashboardSupportTicketsRouteChildren: DashboardSupportTicketsRouteChildren =
  {
    DashboardSupportTicketsIdRoute: DashboardSupportTicketsIdRoute,
  }

const DashboardSupportTicketsRouteWithChildren =
  DashboardSupportTicketsRoute._addFileChildren(
    DashboardSupportTicketsRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardEditProfileRoute: typeof DashboardEditProfileRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardPaymentsRoute: typeof DashboardPaymentsRoute
  DashboardPrivacyRoute: typeof DashboardPrivacyRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSubscriptionRoute: typeof DashboardSubscriptionRoute
  DashboardSupportRoute: typeof DashboardSupportRoute
  DashboardSupportTicketsRoute: typeof DashboardSupportTicketsRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardEditProfileRoute: DashboardEditProfileRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardPaymentsRoute: DashboardPaymentsRoute,
  DashboardPrivacyRoute: DashboardPrivacyRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSubscriptionRoute: DashboardSubscriptionRoute,
  DashboardSupportRoute: DashboardSupportRoute,
  DashboardSupportTicketsRoute: DashboardSupportTicketsRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface StaffRouteChildren {
  StaffCreateUserRoute: typeof StaffCreateUserRoute
  StaffEditProfileRoute: typeof StaffEditProfileRoute
  StaffLeadsRoute: typeof StaffLeadsRoute
  StaffNotesRoute: typeof StaffNotesRoute
  StaffUsersRoute: typeof StaffUsersRoute
  StaffIndexRoute: typeof StaffIndexRoute
  StaffLeadIdRoute: typeof StaffLeadIdRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffCreateUserRoute: StaffCreateUserRoute,
  StaffEditProfileRoute: StaffEditProfileRoute,
  StaffLeadsRoute: StaffLeadsRoute,
  StaffNotesRoute: StaffNotesRoute,
  StaffUsersRoute: StaffUsersRoute,
  StaffIndexRoute: StaffIndexRoute,
  StaffLeadIdRoute: StaffLeadIdRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

interface UkControlStaffRouteChildren {
  UkControlStaffIdRoute: typeof UkControlStaffIdRoute
}

const UkControlStaffRouteChildren: UkControlStaffRouteChildren = {
  UkControlStaffIdRoute: UkControlStaffIdRoute,
}

const UkControlStaffRouteWithChildren = UkControlStaffRoute._addFileChildren(
  UkControlStaffRouteChildren,
)

interface UkControlRouteChildren {
  UkControlBulkUploadRoute: typeof UkControlBulkUploadRoute
  UkControlCmsRoute: typeof UkControlCmsRoute
  UkControlEditProfileRoute: typeof UkControlEditProfileRoute
  UkControlLeadsRoute: typeof UkControlLeadsRoute
  UkControlPaymentsRoute: typeof UkControlPaymentsRoute
  UkControlReportsRoute: typeof UkControlReportsRoute
  UkControlStaffRoute: typeof UkControlStaffRouteWithChildren
  UkControlSupportTicketsRoute: typeof UkControlSupportTicketsRoute
  UkControlUsersRoute: typeof UkControlUsersRoute
  UkControlIndexRoute: typeof UkControlIndexRoute
}

const UkControlRouteChildren: UkControlRouteChildren = {
  UkControlBulkUploadRoute: UkControlBulkUploadRoute,
  UkControlCmsRoute: UkControlCmsRoute,
  UkControlEditProfileRoute: UkControlEditProfileRoute,
  UkControlLeadsRoute: UkControlLeadsRoute,
  UkControlPaymentsRoute: UkControlPaymentsRoute,
  UkControlReportsRoute: UkControlReportsRoute,
  UkControlStaffRoute: UkControlStaffRouteWithChildren,
  UkControlSupportTicketsRoute: UkControlSupportTicketsRoute,
  UkControlUsersRoute: UkControlUsersRoute,
  UkControlIndexRoute: UkControlIndexRoute,
}

const UkControlRouteWithChildren = UkControlRoute._addFileChildren(
  UkControlRouteChildren,
)

interface ProfileIdRouteChildren {
  ProfileIdPoruthamRoute: typeof ProfileIdPoruthamRoute
}

const ProfileIdRouteChildren: ProfileIdRouteChildren = {
  ProfileIdPoruthamRoute: ProfileIdPoruthamRoute,
}

const ProfileIdRouteWithChildren = ProfileIdRoute._addFileChildren(
  ProfileIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BrowseRoute: BrowseRoute,
  CompleteProfileRoute: CompleteProfileRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InterestsReceivedRoute: InterestsReceivedRoute,
  InterestsSentRoute: InterestsSentRoute,
  LoginRoute: LoginRoute,
  OtpRoute: OtpRoute,
  PremiumMembersRoute: PremiumMembersRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RecentlyJoinedRoute: RecentlyJoinedRoute,
  RegisterRoute: RegisterRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  StaffRoute: StaffRouteWithChildren,
  SuccessStoriesRoute: SuccessStoriesRoute,
  TermsRoute: TermsRoute,
  UkControlRoute: UkControlRouteWithChildren,
  BlogSlugRoute: BlogSlugRoute,
  ProfileIdRoute: ProfileIdRouteWithChildren,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
